name: CI

on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.102' # SDK Version to use.
    - run: git fetch --unshallow 
    - run: dotnet build 
    - run: dotnet nuget push "bin/Release/WPF2274Workaround*.nupkg" --source "github"
