name: CI

on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      name: checkout
    - uses: actions/setup-dotnet@v1
      name: setup .net sdk
      with:
        dotnet-version: '3.1.102' # SDK Version to use.
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: NuGet/setup-nuget@v1.0.2
      name: Setup NuGet.exe for use with actions
    - run: | 
        git fetch --unshallow
      name: Fetch sources
    - run: | 
        dotnet build -c Release
      name: build
    - run: |
        nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/vatsan-madhavan/index.json" 
        nuget setApiKey ${{ secrets.GITHUB_TOKEN }} -Source "https://nuget.pkg.github.com/MY_ACCOUNT/index.json"
        nuget push bin\Release\*.nupkg --source github 
      name: push packages to GitHub Package Registry
    
