name: CI

on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.102' # SDK Version to use.
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - run: git fetch --unshallow 
    - run: dotnet build -c Release
    - run: powershell -command "Get-ChildItem -Path bin\Release\*.nupkg | % { dotnet nuget push $_.FullName --source github --api-key '${{ secrets.GITHUB_TOKEN }}' }"
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
